{{- if and .Values.cronjobs.enabled .Values.cronjobs.jobs }}
{{- range $i, $job := .Values.cronjobs.jobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "hp-app.fullname" $ }}-{{ $job.name }}
  labels:
    {{- include "hp-app.labels" $ | nindent 4 }}
spec:
  schedule: {{ $job.schedule | quote }}
  suspend: {{ default false $job.suspend }}
  concurrencyPolicy: {{ default "Forbid" $job.concurrencyPolicy }}
  {{- with $job.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  successfulJobsHistoryLimit: {{ default 3 $job.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 3 $job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ default 600 $job.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            {{- include "hp-app.selectorLabels" $ | nindent 12 }}
            {{- with $job.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with $job.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "hp-app.serviceAccountName" $ }}
          {{- with $.Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          containers:
            - name: {{ $job.name }}
              {{- $img := dict "image" $job.image "Values" $.Values "Chart" $.Chart "Release" $.Release "Capabilities" $.Capabilities }}
              {{- $parsed := include "hp-app.image" $img | fromYaml }}
              image: "{{ $parsed.repository }}:{{ $parsed.tag }}"
              imagePullPolicy: {{ $parsed.pullPolicy }}

              {{- with $job.command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $job.args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}

              env:
                {{- range $.Values.global.env }}
                - name: {{ .name }}
                  value: {{ .value | quote }}
                {{- end }}
                {{- range $job.env }}
                - name: {{ .name }}
                  value: {{ .value | quote }}
                {{- end }}

              {{- $cfgs := concat (default (list) $.Values.global.envFrom.configMaps) (default (list) $job.envFrom.configMaps) }}
              {{- $secs := concat (default (list) $.Values.global.envFrom.secrets) (default (list) $job.envFrom.secrets) }}

              {{- if or $cfgs $secs }}
              envFrom:
                {{- range $cfgs }}
                - configMapRef:
                    name: {{ . | quote }}
                {{- end }}
                {{- range $secs }}
                - secretRef:
                    name: {{ . | quote }}
                {{- end }}
              {{- end }}

              resources:
                {{- default $.Values.global.resources $job.resources | toYaml | nindent 16 }}

              {{- with $job.extraVolumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}

          {{- with $job.extraVolumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with $job.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
{{- end }}
{{- end }}
