{{- if and .Values.secrets.enabled .Values.secrets.items }}
{{- range .Values.secrets.items }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "hp-app.labels" $ | nindent 4 }}
type: {{ default "Opaque" .type }}
{{- if .data }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
{{- if .stringData }}
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}
---
{{- end }}
{{- end }}
